// <auto-generated />
namespace LPCopiers.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class extras : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(extras));
        
        string IMigrationMetadata.Id
        {
            get { return "201403221436461_extras"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
