// <auto-generated />
namespace LPCopiers.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class EquipmentTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EquipmentTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201403271118222_EquipmentTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
