// <auto-generated />
namespace LPCopiers.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addedStaffEmail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedStaffEmail));
        
        string IMigrationMetadata.Id
        {
            get { return "201404021849360_addedStaffEmail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
